# Set the base image to Python
FROM python:2.7-onbuild

# File Author / Maintainer
MAINTAINER Petar Vorotnikov

# The requirements will be coppied on build and
# pip install will be executed by the base image
# docker file

# All files will be copied to /usr/src/app
# by the base image docker file

ENV API_KEY=
ENV PUBLIC_KEY=

# Run app
CMD ["python", "main.py"]
