# Set the base image to Python
FROM python:2.7-onbuild

# File Author / Maintainer
MAINTAINER Petar Vorotnikov

# The requirements will be coppied on build and
# pip install will be executed by the base image
# docker file

# All files will be copiet to /usr/src/app
# by the base image docker file

# Run app
CMD ["python", "main.py -w 50"]
